# Nixpacks configuration for Laravel on Railway
# Disable Railpack auto-detection to have full control

[variables]
NIXPACKS_NO_MUSL = "1"

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20"]

[phases.install]
cmds = [
  # Install PHP dependencies WITHOUT dev packages, ignore platform requirements
  "composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs",
  # Install Node dependencies
  "npm ci"
]

[phases.build]
cmds = [
  # Build frontend assets
  "npm run build",
  # Create Laravel directories
  "mkdir -p storage/framework/{sessions,views,cache,testing}",
  "mkdir -p storage/logs",
  "mkdir -p bootstrap/cache",
  # Set permissions
  "chmod -R 775 storage bootstrap/cache",
  # Cache Laravel
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
